### PR TITLE
Eliminate ambiguities

### LINKED ISSUE #21: New method ambiguities for `rem(::SafeUnsigned, ::Base.BitSigned)` and others
Version 3 introduced new method ambiguities:
```julia
julia> rem(SafeUInt(1), 1)
ERROR: MethodError: rem(::SafeUInt64, ::Int64) is ambiguous. Candidates:
  rem(x::T1, y::T2) where {T1<:SafeInteger, T2<:Integer} in SaferIntegers at /home/sebastian/.julia/packages/SaferIntegers/eaDK3/src/arith_ops.jl:64
  rem(x::Unsigned, y::Union{Int128, Int16, Int32, Int64, Int8}) in Base at int.jl:205
Possible fix, define
  rem(::T1, ::T2) where {T1<:SafeUnsigned, T2<:Union{Int128, Int16, Int32, Int64, Int8}}
Stacktrace:
[...]
```
The same ambiguities exist for `mod`, `div`, `cld`, `fld`, `divrem`.

`Test.detect_ambiguities` reveals that there are quite a number of ambiguities:
```julia
julia> Test.detect_ambiguities(SaferIntegers, Base)
110-element Vector{Tuple{Method, Method}}:
[...]
```

### PR DESCRIPTION
**Pull request by mkitti**
Fix #21

### CODE REVIEW

**Comment by mkitti** [comment]
With this PR, I currently get:
```julia
julia> Test.detect_ambiguities(SaferIntegers)
Tuple{Method, Method}[]
```

Also all tests pass:
```julia
     Testing Running tests...
Test Summary: | Pass  Total
construct0    |   10     10
Test Summary: | Pass  Total
construct1    |  100    100
Test Summary: | Pass  Total
construct2    |    7      7
Test Summary: | Pass  Total
construct3    |   30     30
Test Summary: | Pass  Total
construct 4   |   10     10
Test Summary:  | Pass  Total
checked signed |   20     20
Test Summary:    | Pass  Total
checked unsigned |   20     20
Test Summary: | Pass  Total
throw         |   80     80
Test Summary: | Pass  Total
-unsigned     |    6      6
Test Summary: | Pass  Total
float         |    2      2
Test Summary: | Pass  Total
constructors  |    8      8
Test Summary: | Pass  Total
comparisons   |   24     24
Test Summary: | Pass  Total
boolean       |   14     14
Test Summary: | Pass  Total
arithmetic    |   52     52
Test Summary:             | Pass  Total
checked signed arithmetic |   24     24
Test Summary:               | Pass  Total
checked unsigned arithmetic |   22     22
Test Summary:            | Pass  Total
checked mixed arithmetic |   16     16
Test Summary:                       | Pass  Total
checked safe with unsafe arithmetic |   16     16
Test Summary: | Pass  Total
divide        |   11     11
Test Summary: | Pass  Total
number theory |   19     19
Test Summary: | Pass  Total
int ops       |   23     23
Test Summary: | Pass  Total
shifts        |   20     20
Test Summary: | Pass  Total
power         |   15     15
Test Summary: | Pass  Total
factorial     |    2      2
Test Summary: | Pass  Total
rational      |    3      3
Test Summary: | Pass  Total
string        |    2      2
Test Summary: | Pass  Total
ambiguities   |    1      1
     Testing SaferIntegers tests passed 
```

**Comment by mkitti** [comment]
What is left to do is examine the changes and see if they can be made more systematic. Also, perhaps we need to add some tests cases to check the previous ambiguities and also ensure functionality.

**Comment by JeffreySarnoff** [comment]
Thanks for the prompt attention, please stay on it -- I will merge asap

**Comment by mkitti** [comment]
Closing since the changes were incorporated elsewhere.

**Pull request closed without merging**
